# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Kevin
tagline:          'A Game Developer'
description:      'A Game Developer'
url:              https://kevinfyc.github.io
baseurl:          /

#category
cate:
  misc:			  misc
  tech:			  tech
  hidden:     hidden

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
